variables:
  GIT_SUBMODULE_STRATEGY: recursive

  BUILD_MKSHAPESRDF:
    value: "true"
    options:
      - "false"
      - "true"
    description: "Whether to (re)build mkShapesRDF before testing the LCG release. Otherwise builds are taken from previously cached runs."

  TEST_ERA:
    value: "all"
    options:
      - "all"
      - "Full2022v12"
      - "Full2022EEv12"
      - "Full2023v12"
      - "Full2023BPixv12"
      - "Full2024v15"
    description: "Which era(s) to test."

  TEST_STEP:
    value: "all"
    options:
      - "all"
      - "postprocessing"
      - "mkshapes"
      - "mkplots"
      - "none"
    description: "Which analysis step(s) to test. 'none' triggers all preparation steps to run."
